version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: 770760.ru
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=770760.ru
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=770760.ru
      - LETSENCRYPT_EMAIL=ovc@digit-it.ru
    volumes:
      - ${PWD}/public:/usr/share/nginx/html:ro
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external:
      name: nginx-proxy